version: '2'
services:
    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=user_1
            - MYSQL_PASSWORD=user_1
        volumes:
            - mysql-data:/var/lib/mysql

    nginx:
        image: my_nginx
        ports:
            - "80:80" # http
            - "443:443" # https
            - "1025:25" # smtp
        volumes:
            - ${PWD}/app:/usr/share/nginx/html
        links:
            - mysql
        depends_on:
            - mysql
        command: [nginx, '-g', 'daemon off;']

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8888:80"
        links:
            - mysql
        depends_on:
            - mysql
        environment:
            - PMA_HOST=mysql

volumes:
    mysql-data:
